SET FOREIGN_KEY_CHECKS=0;




CREATE TABLE BASE_ACCESS_USER
(
	AUID BIGINT NOT NULL,
	APP_ID BIGINT NOT NULL,
	IP_ADDRESS VARCHAR(50),
	NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	MOBILE VARCHAR(50),
	ACCESS_TIME BIGINT,
	SESSION_ID VARCHAR(200),
	ACCEPT_LANGUAGE VARCHAR(50),
	USER_AGENT VARCHAR(255),
	REFERER VARCHAR(255),
	PRIMARY KEY (AUID, APP_ID),
	KEY (APP_ID)
) 
;


CREATE TABLE BASE_APPLICATION
(
	APP_ID BIGINT NOT NULL,
	UID BIGINT,
	NAME VARCHAR(100),
	DOMAIN VARCHAR(255),
	APP_TYPE INTEGER,
	LOGO_URL VARCHAR(55),
	WELCOME_MESSAGE VARCHAR(255),
	APP_KEY VARCHAR(255) NOT NULL,
	CREATE_TIME BIGINT,
	LAST_UPDATE_TIME BIGINT,
	INDUSTRY_CATEGORY VARCHAR(50),
	PRIMARY KEY (APP_ID),
	UNIQUE UQ_APPLICATION_APP_KEY(APP_KEY),
	KEY (UID)
) 
;


CREATE TABLE BASE_DIALOG_LOG
(
	APP_ID BIGINT NOT NULL,
	SUID BIGINT NOT NULL,
	CREATE_TIME BIGINT NOT NULL,
	AUID BIGINT,
	DIRECTION INTEGER,
	CONTENT_TYPE INTEGER,
	CONTENT TEXT,
	DIALOG_MODE INTEGER
) 
;


CREATE TABLE BASE_IP_LOCATION
(
	IP_ADDRESS VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(255),
	ADDRESS_SIMPLE VARCHAR(255),
	ADDRESS_DETAIL VARCHAR(255),
	PROVINCE VARCHAR(255),
	CITY VARCHAR(255),
	CITY_CODE VARCHAR(50),
	DISTRICT VARCHAR(255),
	STREET VARCHAR(255),
	STREET_NUMBER VARCHAR(255),
	LATITUDE VARCHAR(50),
	LONGITUDE VARCHAR(50),
	ISP VARCHAR(50),
	INSERT_DATE BIGINT,
	NATION VARCHAR(50),
	PRIMARY KEY (IP_ADDRESS)
) 
;


CREATE TABLE BASE_STAFF
(
	SUID BIGINT NOT NULL,
	USER_NAME VARCHAR(255),
	EMAIL VARCHAR(100),
	PASSWORD VARCHAR(255),
	CAN_SERVE CHAR(1),
	LAST_ACTIVE_DATE BIGINT,
	IS_ADMIN CHAR(1),
	UID BIGINT,
	SERVICE_MODE INTEGER,
	SERVICE_CONCURRENT_LIMITED INTEGER DEFAULT 1,
	CREATE_DATE BIGINT,
	PRIMARY KEY (SUID),
	UNIQUE UQ_STAFF_USER_NAME(USER_NAME),
	KEY (UID)
) 
;


CREATE TABLE BASE_STAFF_APP_RELATION
(
	APP_ID BIGINT NOT NULL,
	SUID BIGINT NOT NULL,
	CREATE_TIME BIGINT,
	PRIMARY KEY (APP_ID, SUID),
	KEY (APP_ID),
	KEY (SUID)
) 
;


CREATE TABLE BASE_USER
(
	UID BIGINT NOT NULL,
	NAME VARCHAR(255),
	USER_TYPE INTEGER,
	STAFF_LIMITED INTEGER,
	STAFF_USED INTEGER,
	CREATE_DATE BIGINT,
	LOGO_URL VARCHAR(255),
	SERVICE_MODE INTEGER,
	SERVICE_CONCURRENT_LIMITED INTEGER DEFAULT 1,
	PRIMARY KEY (UID)
) 
;



SET FOREIGN_KEY_CHECKS=1;


ALTER TABLE BASE_ACCESS_USER ADD CONSTRAINT FK_ACCESSUSER_APPLICATION 
	FOREIGN KEY (APP_ID) REFERENCES BASE_APPLICATION (APP_ID)
;

ALTER TABLE BASE_APPLICATION ADD CONSTRAINT FK_APPLICATION_USER 
	FOREIGN KEY (UID) REFERENCES BASE_USER (UID)
;

ALTER TABLE BASE_STAFF ADD CONSTRAINT FK_STAFF_USER 
	FOREIGN KEY (UID) REFERENCES BASE_USER (UID)
;

ALTER TABLE BASE_STAFF_APP_RELATION ADD CONSTRAINT FK_STAFFAPPRELATION_APPLICATION 
	FOREIGN KEY (APP_ID) REFERENCES BASE_APPLICATION (APP_ID)
;

ALTER TABLE BASE_STAFF_APP_RELATION ADD CONSTRAINT FK_STAFFAPPRELATION_STAFF 
	FOREIGN KEY (SUID) REFERENCES BASE_STAFF (SUID)
;
