SET FOREIGN_KEY_CHECKS=0;




CREATE TABLE TAG_OBJECT_CATEGORY
(
	ID BIGINT NOT NULL,
	NAME VARCHAR(100),
	CREATE_DATE BIGINT,
	DESCRIPTION VARCHAR(100),
	LAST_UPDATE_DATE BIGINT,
	PRIMARY KEY (ID)
) 
;


CREATE TABLE TAG_TAG_CATEGORY
(
	ID BIGINT NOT NULL,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(255),
	LOCALE VARCHAR(50),
	CREATE_DATE BIGINT,
	LAST_UPDATE_DATE BIGINT,
	PRIMARY KEY (ID)
) 
;


CREATE TABLE TAG_TAG_OBJECT_RELATION
(
	TAG_ID BIGINT NOT NULL,
	OBJECT_ID BIGINT NOT NULL,
	OBJECT_CATEGORY_ID BIGINT NOT NULL,
	WEIGHT BIGINT,
	CREATE_DATE BIGINT,
	PRIMARY KEY (TAG_ID, OBJECT_ID, OBJECT_CATEGORY_ID),
	KEY (OBJECT_CATEGORY_ID),
	KEY (TAG_ID)
) 
;


CREATE TABLE TAG_TAGS
(
	ID BIGINT NOT NULL,
	NAME VARCHAR(50),
	LOCALE VARCHAR(50),
	CATEGORY_ID BIGINT,
	WEIGHT BIGINT,
	CREATE_DATE BIGINT,
	PRIMARY KEY (ID),
	KEY (CATEGORY_ID)
) 
;



SET FOREIGN_KEY_CHECKS=1;


ALTER TABLE TAG_TAG_OBJECT_RELATION ADD CONSTRAINT FK_TAG_OBJECT_RELATION_OBJECT_CATEGORY 
	FOREIGN KEY (OBJECT_CATEGORY_ID) REFERENCES TAG_OBJECT_CATEGORY (ID)
;

ALTER TABLE TAG_TAG_OBJECT_RELATION ADD CONSTRAINT FK_TAG_OBJECT_RELATION_TAG 
	FOREIGN KEY (TAG_ID) REFERENCES TAG_TAGS (ID)
;

ALTER TABLE TAG_TAGS ADD CONSTRAINT FK_TAG_TAG_CATEGORY 
	FOREIGN KEY (CATEGORY_ID) REFERENCES TAG_TAG_CATEGORY (ID)
;
